---
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: example-app
description: exampl-app application pipeline
serialPipeline:
  stages:
  - targetId: prd
    profiles:
    - prd
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prd
description: production cluster
gke:
  cluster: projects/gcpug-shonan-202302-demo/locations/asia-northeast1-a/clusters/demo
executionConfigs:
- defaultPool:
    serviceAccount: "deployer@gcpug-shonan-202302-demo.iam.gserviceaccount.com"
  usages:
  - DEPLOY
  - RENDER
