apiVersion: v1
kind: Service
metadata:
  name: example
  labels:
    app: example
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-app
  selector:
    app: example
  type: ClusterIP
