---
apiVersion: monitoring.googleapis.com/v1alpha1
kind: PodMonitoring
metadata:
  name: example
spec:
  endpoints:
  - interval: 15s
    port: http-app
    path: /metrics
  selector:
    matchLabels:
      app: example
  targetLabels:
    fromPod:
    - from: app
      to: app
