---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        env: qa
    spec:
      serviceAccountName: example-qa
      containers:
      - name: app
        image: gcr.io/gcpug-shonan-202302-demo-2/example-app:v1
